apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rs5tsmx8b-nodejs
  janus-idp.io/tekton: rs5tsmx8b-nodejs
  backstage.io/kubernetes-id: rs5tsmx8b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rs5tsmx8b-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
